### ISSUE TITLE
who/what is responsible for declaring and monitoring `data_portal_subset` elements?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1342]
This is a question about using subsets to let responsible parties know when a change in modeling may effect portal functionality.

The nmdc-schema has a `data_portal_subset`. It is documented on this page: https://microbiomedata.github.io/nmdc-schema/DataPortalSubset/

```yaml
data_portal_subset:
  description:
    Subset consisting of entities that Kitware/nmdc-server use to populate the data portal.
  comments:
    - Schema authors are responsible for alerting and supporting Kitware and nmdc-server authors 
      about changes they will have to make if entities labeled with data_portal_subset are modified.
    - Assignment of the data_portal_subset is incomplete in the schema.
```

**I really like the spirit of this subset, but am concerned that** 
- the way it is being applied to schema elements is inconsistent 
- the communication responsibilities are be easy to forget.

For example, when the DOI modelling was changed from multiple free standing slots to a class, that had an impact of the SubmissionPortal. Should we have a submission_portal_subset? Who communicate the new modeling to SubmissionPortal maintainers?

----

## sub-issues about the subset documentation pages:

- [ ] the documentation page changes the case from `data_portal_subset` to DataPortalSubset
- [ ] the documentation page does not display the `description` or `comments`.
- [ ] the documentation page lists the slots that are in the subset. If classes had been placed into the subset, would they also appear on the page?

**Comment by turbomam** [comment]
Flagging that `src/schema/nmdc_subsets.yaml`, which declares `data_portal_subset`, is proposed for deletion in https://github.com/microbiomedata/nmdc-schema/pull/3338 (Delete the unimported src/schema/nmdc_subsets.yaml).

That does not resolve this question, and it is not meant to. The file was never imported into the merged schema and no element ever carried `in_subset: data_portal_subset`, so the mechanism described here has not been in effect. The concerns raised above (inconsistent application, and communication responsibilities being easy to forget) are exactly why it stayed empty.

The question is live again for a concrete reason: metadata-quality badges are a portal-facing schema feature, and the data portal is implementing display against them now in https://github.com/microbiomedata/nmdc-server/issues/2314 (Implement metadata quality visualizations on the data portal). So "which schema elements does the portal depend on, and who tells the portal team when they change" has a current example rather than a hypothetical one.

If the answer is that a subset is the right mechanism, it should be declared in a module that is actually imported, alongside `jgi_isolate` and the badge subsets in `basic_slots.yaml`, and applied exhaustively rather than partially.
