### ISSUE TITLE
Refactor `PersonValue` and credit roles (i.e. the permissible values of `CreditEnum`)

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1437]
How people are captured and managed by the NMDC schema and data portal need refactored.

- [x] [ relationship between Person, PersonValue and Agent](https://github.com/microbiomedata/nmdc-schema/issues/895)

- [ ] Deprecate the PI slot and leverage the PI credit role for the data portal
 https://github.com/microbiomedata/nmdc-schema/issues/458 & https://github.com/microbiomedata/nmdc-schema/issues/301

- [ ] #855 

- [ ] Remove "submitter" from credit roles, Submission permission levels don't need to be captured by the schema.

**Comment by turbomam** [comment]
I'm editing the title of this issue so that it matches the actual names of the schema elements under discussion
