### ISSUE TITLE
`berkeley-schema-fy24`: Finalize names of Berkeley schema migrators

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1983]
#### Tasks

- [x] Determine what the initial Berkeley schema version will be (I think it will be `11.0.0`)
- [x] Determine the order in which the Berkeley schema migrators were designed to be run (that is documented in [this issue description](https://github.com/microbiomedata/nmdc-schema/issues/1607#issue-2058837721))
- [ ] ~For each Berkeley schema migrator, update its module name and `_from_version` and `_to_version` variables to reflect the preceding and succeeding migrators' names~
  - Special case 1: For the initial migrator, set its `_from_version` to be the origin schema version number (e.g. `10.3.0`)
  - Special case 2: For the final migrator, set its `_to_version` to be the destination schema version number (e.g. `11.0.0`)
- [ ] ~For each Berkeley schema migrator, update its file name to reflect the new preceding/succeeding migrators or schema versions~
  - If applicable, update its `assets` directory to reflect its new name

#### Background

Currently, Berkeley schema migrators have names like `migrator_from_X_to_PR9` because (a) we didn't know what order they'd be run in and (b) we didn't know what the starting and ending schema versions would be.

CC: @brynnz22 and @turbomam

**Comment by ssarrafan** [comment]
@eecavanna I know you were working on this.  Should it be moved to the next sprint or do you think it'll be done today?

**Comment by eecavanna** [comment]
Hi @ssarrafan, I think it will be done today.

**Comment by eecavanna** [comment]
I will move this to the next sprint after all. I expect to have implemented it in a PR today, but I don't think that PR will be merged into `berkeley-schema-fy24/main` today (one of the people I will want to review it is out today).

**Comment by eecavanna** [comment]
I implemented this in https://github.com/microbiomedata/berkeley-schema-fy24/pull/218 (awaiting review/merge). The merging of that PR might be dependent upon approval from the Berkeley schema roll out squad members, since we're in a "schema freeze" period and the migrators happen to live in the same repo as the schema.

**Comment by ssarrafan** [comment]
@eecavanna so should this be in the backlog for now?

**Comment by eecavanna** [comment]
I'd prefer it be in the next sprint, in the column that indicates it's being reviewed. 

I do expect it to be merged in even though we're in this freeze period. The squad members just introduced this additional administrative step in an attempt to prevent accidentally breaking things downstream from the schema.
