### ISSUE TITLE
Generate sediment DH interface

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#284]
But don't repeat cheats from constructing the soil templates. Specifically, [use "exhaustion" dependency resolution](https://github.com/microbiomedata/sheets_and_friends/pull/80), instead of hard-coding an imported slot's recursive type, class or enum dependencies into nmdc-dh-sheets. 

Sheets and friends will be getting larger. Might be helpful to replicate `all` metaterm that @mslarae13 had in [SNTC](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0). That will probably be easier for the import shuttling phase than for the new terms (schemasheets) phase

PS Initially, should this include emsl and jgi terms?

**Comment by mslarae13** [comment]
I do not think we should include EMSL and JGI terms for the packages that we have not "curated" I say this because they will not match what I have done for EMSL.

@emileyfadrosh  thoughts?

**Comment by turbomam** [comment]
> I do not think we should include EMSL and JGI terms for the packages that we have not "curated" I say this because they will not match what I have done for EMSL.

Thanks. I agree. 

**The sediment interface is done**, [along with the other 10 interfaces that were requested](https://docs.google.com/document/d/1W0Nd-nGLEUbJ8KAPEZO5M1JNYGbvFbgFdaSwlkpnajI/edit#bookmark=id.3tji971lfj37), plus [built environment](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=1963017587)

- The modeling is in [nmdc-dh-sheets-mam-non-anno](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8) 
  - I'll be changing the name soon but the sheet ID will remain the same
- The code to process this is in the [main branch of sheets_and_friends](https://github.com/microbiomedata/sheets_and_friends)
- these new interfaces do not include any EMLS or JGI slots. The don't include soil_emls_jgi_mg's [MIxS inspired](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=1834404667&range=8:8) terms either.
- the new interfaces do currently reuse all of the slots/columns from the Sample ID section. For any MIxS slots that were modified for soil_emsl_jgi_mg and are also used for the env_packages modelled in the new DH interfaces, all of the modifications have been retained.
- MIxS slots for the new env_package interfaces are going into a section called "MIxS core", to keep them separate from the MIxS section from the soil_emsl_jgi_mg interface.
- In order to keep repetitive typing to a minimal and to keep the sheets small, pipe separators can now be used to assign slots to interface classes on most tabs. There are also `mixin` modules for reusable blacks of slots (like EMSL, JGI, etc.) The [mixin_slots](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=667012330) tab replaces what was previously called "new terms" 
- I don't have good way of sharing a single build that includes all of these new env_apckage interfaces **and** has them arranged into sections as specified in the Google sheet. Part of that is due to [unfinished work](https://github.com/cidgoh/DataHarmonizer/issues/276) between Damion, @sujaypatil96 and @turbomam. Some of it due to the tight coupling between [sheets_and_friends' GH pages](https://microbiomedata.github.io/sheets_and_friends/main.html) and the [sample submission portal](https://data.microbiomedata.org/submission/samples). I think @subdavis is starting to think of ways that we could have two static content web servers, only one of which would be coupled to the sample submission portal. GH pages and [netlify](https://www.netlify.com/github-pages-vs-netlify)?
- The MIxS environmental triad columns for the new env_package interfaces are populated with the same term subsets as the soil_emsl_jgi_mg interface. That's partially due to the limited curation for the other env_pacakges.

## Todo for MIxS environmental triad *processing*
- [ ] @turbomam bootstrap the curation by extracting the terms that are most frequently used for the other env_packages in our INSDC biosample_set SQLite database [biosample_basex.db.gz](https://portal.nersc.gov/project/m3513/biosample/?C=M;O=D)
- [ ] @turbomam work on the [hierarchical indentation code](https://github.com/turbomam/hident) to make sure that the level of indentation is correct when intermediate subclasses have been excluded, etc.
- [ ] @turbomam convert the current [outrageous shell scripting commands](https://github.com/microbiomedata/sheets_and_friends/blob/0cfeba3c5653cb1ad197f47dada0a376b9d3525a/Makefile#L103-L107) for extracting the curated subsets from the Google Sheet into a python script
- [ ] @turbomam parameterize the [hident invocation ](https://github.com/microbiomedata/sheets_and_friends/blob/0cfeba3c5653cb1ad197f47dada0a376b9d3525a/Makefile#L111-L139) so that a separate Makefile rule isn't required for each package X triad slot

## Also, related to GH pages.sample submission coupling
- [ ] The sample submission portal broke on. my last push to master. I think I know how to fix and will work on it right now.

> "template/soil_emsl_jgi_mg/data.js". Is the template name correct?
 
@sujaypatil96 do you think I misrepresented anything or left anything important out?

@cmungall CC'ing you so you can see what the heck we're working on

**Comment by ssarrafan** [comment]
I'm closing this issue per @turbomam because the sediment is done. Mark would like  @emileyfadrosh @mslarae13 @cmungall @sujaypatil96 to please review the comments.

**Comment by emileyfadrosh** [comment]
Thanks @turbomam ! This looks great, and agree with all the next steps. Probably several new tickets need to be generated for all the to-do items :) We should prioritize the environmental triad processing, and then @mslarae13 we should talk about EMSL curation for the other packages. 

Nice work!
